### ISSUE TITLE
Change README.md to refer to the images on GitHub Registries

### ISSUE THREAD

**Issue by Leticia-maria** [geem-lab/docker-hpc#7]
*Reminder

The documentation refers to a personal profile in DockerHub. I may switch it to the docker-hpc repository

**Comment by schneiderfelipe** [comment]
This was originally (kind of) a personal project. I'm OK with transfering all images to GitHub or other corporate/organizational profile.

**Comment by Leticia-maria** [comment]
In my opinion, we should refer in our docs to the images on GitHub Registries. It's easier to use. Can I do that (rewrite the README.md), @schneiderfelipe?

**Comment by schneiderfelipe** [comment]
@Leticia-maria Sure, that's a great idea!

**Comment by Leticia-maria** [comment]
Closed by #10
